// main.js
//
// Frontend logic for AlwaysOnTop. Talks to the Go backend exclusively
// through the Wails-generated bindings in ../wailsjs/go/main/App.js,
// which in turn proxy to the Python engine over the JSON-lines IPC
// pipe. This file has zero knowledge of Win32 - it only ever sees the
// plain WindowInfo / result shapes app.go hands back.
//
// NOTE: ../wailsjs/** is auto-generated by the Wails CLI the first time
// you run `wails dev` or `wails build` from the project root - it does
// not need to be (and should not be) hand-written or committed before
// that. See README.md.

import { ListWindows, SetTopmost, MinimizeWindow, CloseWindow } from "../wailsjs/go/main/App.js";
import { EventsOn } from "../wailsjs/runtime/runtime.js";

const REFRESH_INTERVAL_MS = 4000;
const TOAST_DURATION_MS = 3200;

const els = {
  select: document.getElementById("window-select"),
  selectWrapper: document.getElementById("select-wrapper"),
  applyBtn: document.getElementById("btn-apply"),
  removeBtn: document.getElementById("btn-remove"),
  statusText: document.getElementById("status-text"),
  toastContainer: document.getElementById("toast-container"),
  minimizeBtn: document.getElementById("btn-minimize"),
  closeBtn: document.getElementById("btn-close"),
};

/** @type {Map<number, {hwnd:number,title:string,pid:number,process_name:string,topmost:boolean}>} */
let windowsByHwnd = new Map();
let selectedHwnd = null;
let isBusy = false; // true while an Apply/Remove call is in flight
let hasLoadedOnce = false;

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function optionLabel(win) {
  return `${win.title} — ${win.process_name}`;
}

function renderOptions() {
  const previousSelection = selectedHwnd;
  els.select.innerHTML = "";

  if (windowsByHwnd.size === 0) {
    const opt = document.createElement("option");
    opt.value = "";
    opt.textContent = hasLoadedOnce ? "No windows available" : "Loading windows…";
    opt.selected = true;
    els.select.appendChild(opt);
    els.select.disabled = true;
    selectedHwnd = null;
    updateButtonStates();
    return;
  }

  els.select.disabled = false;

  const placeholder = document.createElement("option");
  placeholder.value = "";
  placeholder.textContent = "Select a window…";
  placeholder.hidden = true;
  els.select.appendChild(placeholder);

  let stillPresent = false;
  for (const win of windowsByHwnd.values()) {
    const opt = document.createElement("option");
    opt.value = String(win.hwnd);
    opt.textContent = optionLabel(win);
    if (win.hwnd === previousSelection) {
      opt.selected = true;
      stillPresent = true;
    }
    els.select.appendChild(opt);
  }

  if (!stillPresent) {
    if (previousSelection !== null) {
      // The window the user had selected disappeared (closed, etc.)
      showToast("The selected window closed and was removed from the list.", "info");
    }
    selectedHwnd = null;
    placeholder.selected = true;
  }

  updateButtonStates();
}

function updateButtonStates() {
  const win = selectedHwnd !== null ? windowsByHwnd.get(selectedHwnd) : null;

  els.applyBtn.disabled = isBusy || !win || win.topmost;
  els.removeBtn.disabled = isBusy || !win || !win.topmost;
  els.applyBtn.dataset.active = win && win.topmost ? "true" : "false";
}

function setStatus(text, tone = "muted") {
  els.statusText.textContent = text;
  if (tone === "muted") {
    els.statusText.removeAttribute("data-tone");
  } else {
    els.statusText.dataset.tone = tone;
  }
}

function showToast(message, tone = "info") {
  const toast = document.createElement("div");
  toast.className = "toast";
  toast.dataset.tone = tone;
  toast.setAttribute("role", tone === "error" ? "alert" : "status");
  toast.textContent = message;
  els.toastContainer.appendChild(toast);

  // Force a reflow so the transition actually plays.
  requestAnimationFrame(() => toast.classList.add("toast-visible"));

  setTimeout(() => {
    toast.classList.remove("toast-visible");
    setTimeout(() => toast.remove(), 220);
  }, TOAST_DURATION_MS);
}

// ---------------------------------------------------------------------------
// Data loading
// ---------------------------------------------------------------------------

async function loadWindows({ silent } = { silent: false }) {
  if (!silent) {
    els.select.setAttribute("aria-busy", "true");
  }

  try {
    const result = await ListWindows();

    if (!result || !result.success) {
      const message = (result && result.error) || "Failed to list windows.";
      if (!hasLoadedOnce) {
        setStatus(message, "error");
      }
      showToast(message, "error");
      return;
    }

    windowsByHwnd = new Map((result.windows || []).map((w) => [w.hwnd, w]));
    hasLoadedOnce = true;
    renderOptions();

    const count = windowsByHwnd.size;
    setStatus(`${count} window${count === 1 ? "" : "s"} available`);
  } catch (err) {
    const message = describeError(err);
    if (!hasLoadedOnce) {
      setStatus(message, "error");
    }
    showToast(message, "error");
  } finally {
    els.select.removeAttribute("aria-busy");
  }
}

function describeError(err) {
  if (typeof err === "string") return err;
  if (err && typeof err.message === "string") return err.message;
  return "Something went wrong talking to the engine.";
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

async function applyTopmost(value) {
  if (selectedHwnd === null || isBusy) return;

  const win = windowsByHwnd.get(selectedHwnd);
  if (!win) return;

  isBusy = true;
  updateButtonStates();

  try {
    const result = await SetTopmost(selectedHwnd, value);

    if (!result || !result.success) {
      const message = (result && result.error) || "The operation failed.";
      showToast(message, "error");
      setStatus(message, "error");
      return;
    }

    win.topmost = result.topmost;
    windowsByHwnd.set(selectedHwnd, win);

    if (value) {
      setStatus("Always on top enabled", "success");
      showToast(`"${win.title}" is now always on top.`, "success");
    } else {
      setStatus("Always on top disabled");
      showToast(`"${win.title}" is no longer always on top.`, "info");
    }
  } catch (err) {
    const message = describeError(err);
    showToast(message, "error");
    setStatus(message, "error");
  } finally {
    isBusy = false;
    updateButtonStates();
  }
}

// ---------------------------------------------------------------------------
// Wiring
// ---------------------------------------------------------------------------

els.select.addEventListener("change", (event) => {
  const value = event.target.value;
  selectedHwnd = value === "" ? null : Number(value);
  updateButtonStates();
});

els.applyBtn.addEventListener("click", () => applyTopmost(true));
els.removeBtn.addEventListener("click", () => applyTopmost(false));

els.minimizeBtn.addEventListener("click", () => {
  MinimizeWindow();
});

els.closeBtn.addEventListener("click", () => {
  CloseWindow();
});

// Surface a fatal engine startup failure (e.g. Python not found) without
// a blocking native message box - only truly fatal errors use one, per
// spec, and this isn't unrecoverable from the UI's perspective.
try {
  EventsOn("engine:fatal", (message) => {
    setStatus("Engine unavailable", "error");
    showToast(`Engine error: ${message}`, "error");
  });
} catch {
  // Runtime events are only available inside the Wails webview; ignore
  // if this file is ever loaded outside it (e.g. a quick browser preview).
}

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------

loadWindows({ silent: false });
setInterval(() => loadWindows({ silent: true }), REFRESH_INTERVAL_MS);
