// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function ListWindows() {
  return window['go']['main']['App']['ListWindows']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function SetTopmost(arg1, arg2) {
  return window['go']['main']['App']['SetTopmost'](arg1, arg2);
}
