// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseWindow():Promise<void>;

export function ListWindows():Promise<main.ListWindowsResult>;

export function MinimizeWindow():Promise<void>;

export function SetTopmost(arg1:number,arg2:boolean):Promise<main.SetTopmostResult>;
